coverage:
  status:
    project: true
    patch: true

flag_management:
  individual_flags:
    - name: backend
      paths:
        - Backend/
      statuses:
        - type: project
          target: 80%
          threshold: 1%
        
        - type: patch
          target: 75%
          threshold: 1%

    - name: frontend
      paths:
        - Frontend/
      statuses:
        - type: project
          target: auto # For the meantime, set to "auto" and to change on TPY-18
          threshold: 1%

        - type: patch
          target: auto # For the meantime, set to "auto" and to change on TPY-18
          threshold: 1%