name: Continuous Deployment — Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment"
        required: false
        default: "dev"
        type: choice
        options:
          - dev
          - prod
 
jobs:
  deploy:
    name: Deployment Pipeline
    runs-on: ubuntu-latest
 
    steps:
      - name: Determine target environment
        run: echo "Target environment is -> ${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Download static site artifact
        uses: actions/download-artifact@v8.0.0
        with:
          name: transparity-frontend-artifact
          path: ./Frontend/out

      # - name: Deploy to Cloudflare
      #   uses: cloudflare/wrangler-action@v3.x
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}