name: Continuous Integration — Frontend

on:
  push:
    branches:
      - "master"
    paths:
      - "Frontend/**"
  pull_request:
    branches:
      - "master" 
    paths:
      - "Frontend/**"
  workflow_dispatch:
  
jobs:
  build:
    name: Pipeline Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Frontend

    outputs:
      version: ${{ steps.build_version.outputs.semVer }}

    permissions:
      actions: read
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: Install git version
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: 6.4.x

      - name: Determine build version
        id: build_version
        uses: gittools/actions/gitversion/execute@v4.2.0
        with:
          disableCache: true

      - name: Print build version
        run: echo "This build will be versioned as ${{ steps.build_version.outputs.semVer }}"
    
      - name: Setup target node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Perform dependencies installation
        run: npm ci --prefer-online

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "typescript"

      - name: Build project
        run: npm run build

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: Run unit tests
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./Frontend/coverage/lcov.info"
          fail_ci_if_error: true
          verbose: true
          
      - name: Upload release artifact
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_COMPRESS: gz
          GHR_PATH: ./Frontend/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}